### ISSUE TITLE
URL

### ISSUE THREAD

**Issue by rcoughlan-1980** [52North/ecmwf-dataset-crawl#20]
Please see below a spreadsheet contain URLs for some Agencies that were examined previously which had successful results when looking for real-time data hydrological data.

Any problems let me know or if this is not what you were looking for @noerw let me know.

Thanks

[country_urls.xlsx](https://github.com/52North/ecmwf-dataset-crawl/files/2053887/country_urls.xlsx)

Ruth

**Comment by noerw** [comment]
Yes perfect, that's exactly what I needed. Thanks!

**Comment by noerw** [comment]
@rcoughlan-1980 you mentioned that you have another longer list of data set URLs. Would you mind posting it here / sending it to me?

**Comment by noerw** [comment]
Wow, this is an incredible collection of information. With your explanation I understood the table well, thank you.

I will see how many of the URLs are still working to be used as training data. We can use the specified data types for more fine-grained classification, so that's great!
