### ISSUE TITLE
"Could not get seed URLs: Keywords [] did not yield any seed URLs"

### ISSUE THREAD

**Issue by carletes** [52North/ecmwf-dataset-crawl#26]
Hola, @noerw! We tried using the crawler instance you set up under `xxx.demo.52north.org`. 

We defined a crawl using the following parameters:

* Keyword group 1: "river flood data"
* Keyword group 2: "river level data"
* No common keywords

* Countries: "United Kingdom"
* Languages: "English"
* No tick in "also search with untranslated keywords"

* Crawl depth: 2
* Seed URLs per Keyword group: 30
* Terminate after: 300 minutes, 3000 results

We got the following error:

> Could not get seed URLs: Keywords [] did not yield any seed URLs

Could you perhaps advise why this happened? Are we perhaps using the interface in a wrong way?

**Comment by rcoughlan-1980** [comment]
Hi,

I ran a couple of test there and it turns out that if the tick boxes by the keyword groups is not checked to translate it creates this error.

**Comment by noerw** [comment]
Interesting, will look into it!

**Comment by noerw** [comment]
When none of the keyword groups is to be translated, they will be ignored for the language list.
As you also specified "don't search with untranslated keywords", the result is an empty keyword list.

This is certainly confusing, so for now I disabled the "next"-button, when `search with untranslated keywords` is not ticked.

Instead, when searching in target language English, either enable "search with untranslated keywords" or enable keyword-translation.
