### ISSUE TITLE
Keywords "video, sharing, camera phone, video ..."

### ISSUE THREAD

**Issue by carletes** [52North/ecmwf-dataset-crawl#27]
In crawl "ruth's test 2" (tUtaI2UBpX_22WxhBw7_), some entries have keywords like "video, sharing, camera phone, video ...", which were not specified in the keyword groups.

Question: Were these keywords automatically assigned by the crawler?

**Comment by noerw** [comment]
Hi Carlos,

currently, the crawler assigns some keywords via content analysis (`dataset`, `historic`, `realtime`, `api`, `dataportal`, `datalink`, `pdf`), but also adds all keywords the page has embedded in its `<meta  name="keyword">` tag.
This means arbitrary additional tags can be listed, as they tend to describe the page content
