### ISSUE TITLE
filter result languages, use better language detector

### ISSUE THREAD

**Issue by rcoughlan-1980** [52North/ecmwf-dataset-crawl#29]
Hi Norwin @noerw 

I may be not fully understanding how the crawler works-so forgive me in advance if I have gotten this wrong.

I have just done a crawl for three countries: Andorra, United Arab Emirates, Antigua and Barbuda.

The three translation languages are: Catalan, Arabic and English.

In the web tool results, I am seeing a number of pages which appear to be in English having a translate page from Estonian or Lithuanian.

![image](https://user-images.githubusercontent.com/39592303/44097702-4df9ceca-9fd6-11e8-95d7-a1df979e33ca.png)

Following this, I created a csv  with the results to examine it further and I saw:

- a large number of URLS are identified as various languages even though there content is in English
 
 - URLs where the language is miscalculated for example

http://uetd-hessen.de/?deuir=msn-leute-kennenlernen&f2c=a3                  language: LT  

when in fact it is a german website and in German.

- hosts which are the same have different translated languages assigned to them (same host as above)

http://uetd-hessen.de/?deuir=singlesuche-leer&4e9=06                             language:DE

- URLs for countries Germany, France with the correct language assigned but my crawl is in Catalan, Arabic and English ONLY?

My thoughts are that the three languages that should be pulled back by the crawler should ONLY be Catalan, Arabic and English.  I could be misunderstanding something here could you explain?

Thanks

Ruth

**Comment by rcoughlan-1980** [comment]
I will pop over to @carletes this morning to discus:

how much work is involved in changing change language detector?

**Comment by noerw** [comment]
I would first try out [CLD2](https://github.com/CLD2Owners/cld2) (chrome's language detector which is said to be good, supporting far more languages & can apply hints from domain name and HTML tags).

As this is written in C++, there's additional effort involved, but I'd estimate it would be working after a workday.

**Comment by carletes** [comment]
@noerw: Could you perhaps add a toggle in the results page that only shows the results in the initial languages? That way we do not risk missing out potentially valid results in case Tika gets the language wrong.

Regarding CLD2: It sounds a good idea, but I'm not sure we have much time left for it :( Leave it for the end, I'd suggest, in case you have time left for it
