### ISSUE TITLE
User guide

### ISSUE THREAD

**Issue by rcoughlan-1980** [52North/ecmwf-dataset-crawl#31]
Hi Norwin,

In looking at trying to make a user guide- I have realised that I don't fully understand exactly what each part of the tool means, how changing parameters will affect the crawl, and overall the scope of the abilities of what you have created!!

I think its best if you could put the part together on the technical side (eg. what each button does, check box does, what is depth recursion, how changing it will affect the crawl, etc means) and then I can add the 'How to part' around what you have created.... Maybe you already have this somewhere?

What the user guide needs is a simple approach in explaining as people from different backgrounds/some not as technical as you will be using the tool.

Thanks

Ruth

**Comment by noerw** [comment]
I started an outline [in the wiki](https://github.com/52North/ecmwf-dataset-crawl/wiki/User-Guide) where I will try to outline each feature / button / ..
Can't start this today though.

**Comment by rcoughlan-1980** [comment]
Oh excellent- I will start with this it will give me a bit of a basis!

No rush... I have loads on for another project!

**Comment by noerw** [comment]
I wrote everything down that seems relevant to me on that wiki page, let me know if there are still questions!
