### ISSUE TITLE
Decision on Techstack

### ISSUE THREAD

**Issue by noerw** [52North/ecmwf-dataset-crawl#4]
Decision based on #3:

- [x] Crawler: we went for the stream based approach using the Storm Crawler SDK
    - higher flexibility, better support, better UX
- [x] Persistence: Elasticsearch for all Storage
    - makes indexing and storage simple, avoids another DB dependency
- [x] Translation API: Azure Text Translator
    - works well, plenty free quota
- [x] Search API: ideally Google Custom Search, depending on budget
- [x] Content Extraction: MALLET framework for NLP
    - feature rich, fits into remaining tech stack, plenty documentation

**Comment by carletes** [comment]
Perfect! I'm very curious about Storm Crawler. Elasticsearch's perfect for this, I think.

Regarding the budget for Google Custom Search: We did not get a final answer from managment, but there's still hope :)
